package cbe.inserting.model.auto;

import org.apache.cayenne.CayenneDataObject;

import cbe.inserting.model.Address;

/**
 * Class _Person was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Person extends CayenneDataObject {

    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String USERNAME_PROPERTY = "username";
    public static final String ADDRESS_PROPERTY = "address";

    public static final String ID_PK_COLUMN = "ID";

    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }

    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }

    public void setUsername(String username) {
        writeProperty("username", username);
    }
    public String getUsername() {
        return (String)readProperty("username");
    }

    public void setAddress(Address address) {
        setToOneTarget("address", address, true);
    }

    public Address getAddress() {
        return (Address)readProperty("address");
    }


}
