package cbe.inserting.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Person was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Person extends CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String MODIFY_DATE_PROPERTY = "modifyDate";

    public static final String ID_PK_COLUMN = "id";

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }

    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }

    public void setModifyDate(Date modifyDate) {
        writeProperty("modifyDate", modifyDate);
    }
    public Date getModifyDate() {
        return (Date)readProperty("modifyDate");
    }

    protected abstract void onPreUpdate();

    protected abstract void onPrePersist();

}
