package cbe.inserting.model.auto;

import org.apache.cayenne.CayenneDataObject;

import cbe.inserting.constants.BookType;

/**
 * Class _Book was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Book extends CayenneDataObject {

    public static final String AUTHOR_PROPERTY = "author";
    public static final String ISBN_PROPERTY = "isbn";
    public static final String SEQUENCE_PROPERTY = "sequence";
    public static final String SERIES_PROPERTY = "series";
    public static final String SUB_TITLE_PROPERTY = "subTitle";
    public static final String TITLE_PROPERTY = "title";
    public static final String TYPE_PROPERTY = "type";

    public static final String ID_PK_COLUMN = "id";

    public void setAuthor(String author) {
        writeProperty("author", author);
    }
    public String getAuthor() {
        return (String)readProperty("author");
    }

    public void setIsbn(String isbn) {
        writeProperty("isbn", isbn);
    }
    public String getIsbn() {
        return (String)readProperty("isbn");
    }

    public void setSequence(Integer sequence) {
        writeProperty("sequence", sequence);
    }
    public Integer getSequence() {
        return (Integer)readProperty("sequence");
    }

    public void setSeries(String series) {
        writeProperty("series", series);
    }
    public String getSeries() {
        return (String)readProperty("series");
    }

    public void setSubTitle(String subTitle) {
        writeProperty("subTitle", subTitle);
    }
    public String getSubTitle() {
        return (String)readProperty("subTitle");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setType(BookType type) {
        writeProperty("type", type);
    }
    public BookType getType() {
        return (BookType)readProperty("type");
    }

    protected abstract void initializeType();

}
