package cbe.inserting.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import cbe.inserting.model.Person;

/**
 * Class _Address was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Address extends CayenneDataObject {

    public static final String CITY_PROPERTY = "city";
    public static final String STATE_PROPERTY = "state";
    public static final String STREET_PROPERTY = "street";
    public static final String ZIP_CODE_PROPERTY = "zipCode";
    public static final String PERSON_PROPERTY = "person";

    public static final String ID_PK_COLUMN = "ID";

    public void setCity(String city) {
        writeProperty("city", city);
    }
    public String getCity() {
        return (String)readProperty("city");
    }

    public void setState(String state) {
        writeProperty("state", state);
    }
    public String getState() {
        return (String)readProperty("state");
    }

    public void setStreet(String street) {
        writeProperty("street", street);
    }
    public String getStreet() {
        return (String)readProperty("street");
    }

    public void setZipCode(String zipCode) {
        writeProperty("zipCode", zipCode);
    }
    public String getZipCode() {
        return (String)readProperty("zipCode");
    }

    public void addToPerson(Person obj) {
        addToManyTarget("person", obj, true);
    }
    public void removeFromPerson(Person obj) {
        removeToManyTarget("person", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Person> getPerson() {
        return (List<Person>)readProperty("person");
    }


}
