package cbe.inserting.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import cbe.inserting.model.Role;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String ROLES_PROPERTY = "roles";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToRoles(Role obj) {
        addToManyTarget("roles", obj, true);
    }
    public void removeFromRoles(Role obj) {
        removeToManyTarget("roles", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Role> getRoles() {
        return (List<Role>)readProperty("roles");
    }


}
