package cbe.fetching.model.auto;

import cbe.fetching.model.Designation;

/**
 * Class _Civilian was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Civilian extends Designation {


    public static final String ID_PK_COLUMN = "ID";

}
