package cbe.fetching.model.auto;

import java.util.Date;

import cbe.fetching.model.Designation;

/**
 * Class _Contractor was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contractor extends Designation {

    public static final String COMPANY_NAME_PROPERTY = "companyName";
    public static final String CONTRACT_EXPIRATION_DATE_PROPERTY = "contractExpirationDate";
    public static final String CONTRACT_NUMBER_PROPERTY = "contractNumber";

    public static final String ID_PK_COLUMN = "ID";

    public void setCompanyName(String companyName) {
        writeProperty("companyName", companyName);
    }
    public String getCompanyName() {
        return (String)readProperty("companyName");
    }

    public void setContractExpirationDate(Date contractExpirationDate) {
        writeProperty("contractExpirationDate", contractExpirationDate);
    }
    public Date getContractExpirationDate() {
        return (Date)readProperty("contractExpirationDate");
    }

    public void setContractNumber(String contractNumber) {
        writeProperty("contractNumber", contractNumber);
    }
    public String getContractNumber() {
        return (String)readProperty("contractNumber");
    }

}
