package cbe.fetching.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import cbe.fetching.constants.DesignationType;
import cbe.fetching.model.Person;

/**
 * Class _Designation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Designation extends CayenneDataObject {

    public static final String COMPANY_NAME_PROPERTY = "companyName";
    public static final String CONTRACT_EXPIRATION_DATE_PROPERTY = "contractExpirationDate";
    public static final String CONTRACT_NUMBER_PROPERTY = "contractNumber";
    public static final String PCS_END_DATE_PROPERTY = "pcsEndDate";
    public static final String RANK_PROPERTY = "rank";
    public static final String TYPE_PROPERTY = "type";
    public static final String PERSON_PROPERTY = "person";

    public static final String ID_PK_COLUMN = "ID";

    public void setCompanyName(String companyName) {
        writeProperty("companyName", companyName);
    }
    public String getCompanyName() {
        return (String)readProperty("companyName");
    }

    public void setContractExpirationDate(Date contractExpirationDate) {
        writeProperty("contractExpirationDate", contractExpirationDate);
    }
    public Date getContractExpirationDate() {
        return (Date)readProperty("contractExpirationDate");
    }

    public void setContractNumber(String contractNumber) {
        writeProperty("contractNumber", contractNumber);
    }
    public String getContractNumber() {
        return (String)readProperty("contractNumber");
    }

    public void setPcsEndDate(Date pcsEndDate) {
        writeProperty("pcsEndDate", pcsEndDate);
    }
    public Date getPcsEndDate() {
        return (Date)readProperty("pcsEndDate");
    }

    public void setRank(String rank) {
        writeProperty("rank", rank);
    }
    public String getRank() {
        return (String)readProperty("rank");
    }

    public void setType(DesignationType type) {
        writeProperty("type", type);
    }
    public DesignationType getType() {
        return (DesignationType)readProperty("type");
    }

    public void setPerson(Person person) {
        setToOneTarget("person", person, true);
    }

    public Person getPerson() {
        return (Person)readProperty("person");
    }


    protected abstract void initializeType();

}
