package cbe.fetching.model.auto;

import java.util.Date;

import cbe.fetching.model.Designation;

/**
 * Class _Military was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Military extends Designation {

    public static final String PCS_END_DATE_PROPERTY = "pcsEndDate";
    public static final String RANK_PROPERTY = "rank";

    public static final String ID_PK_COLUMN = "ID";

    public void setPcsEndDate(Date pcsEndDate) {
        writeProperty("pcsEndDate", pcsEndDate);
    }
    public Date getPcsEndDate() {
        return (Date)readProperty("pcsEndDate");
    }

    public void setRank(String rank) {
        writeProperty("rank", rank);
    }
    public String getRank() {
        return (String)readProperty("rank");
    }

}
