package cbe.fetching.model.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Book was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Book extends CayenneDataObject {

    public static final String AUTHOR_PROPERTY = "author";
    public static final String PRICE_PROPERTY = "price";
    public static final String TITLE_PROPERTY = "title";

    public static final String ID_PK_COLUMN = "id";

    public void setAuthor(String author) {
        writeProperty("author", author);
    }
    public String getAuthor() {
        return (String)readProperty("author");
    }

    public void setPrice(BigDecimal price) {
        writeProperty("price", price);
    }
    public BigDecimal getPrice() {
        return (BigDecimal)readProperty("price");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

}
