package cbe.inserting.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * _Person.java was generated by Cayenne.
 *
 * DO NOT EDIT THIS CLASS!
 *
 * _Person.java WILL be overwritten the next time
 * classes are generated.
 *
 * You WILL lose your changes if you manually edit.
 *
 * DO NOT EDIT THIS CLASS!
 *
 * If you need to make any customizations, use the subclass.
 */
public abstract class _Person extends CayenneDataObject
{
    private static final long serialVersionUID = 1L;

    // Attribute Keys
    public static final String EMAIL_ADDRESS_PROPERTY = "emailAddress";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String PASSWORD_PROPERTY = "password";

    // Relationship Keys

    // Primary Keys
    public static final String ID_PK_COLUMN = "id";

    // Attribute Setters/Getters
    public void setEmailAddress(String emailAddress)
    {
        writeProperty(EMAIL_ADDRESS_PROPERTY, emailAddress);
    }
    public String getEmailAddress()
    {
        return (String)readProperty(EMAIL_ADDRESS_PROPERTY);
    }

    public void setFirstName(String firstName)
    {
        writeProperty(FIRST_NAME_PROPERTY, firstName);
    }
    public String getFirstName()
    {
        return (String)readProperty(FIRST_NAME_PROPERTY);
    }

    public void setLastName(String lastName)
    {
        writeProperty(LAST_NAME_PROPERTY, lastName);
    }
    public String getLastName()
    {
        return (String)readProperty(LAST_NAME_PROPERTY);
    }

    public void setPassword(String password)
    {
        writeProperty(PASSWORD_PROPERTY, password);
    }
    public String getPassword()
    {
        return (String)readProperty(PASSWORD_PROPERTY);
    }

    // Relationships
    // Callbacks
}
